import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  backLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    textDecoration: 'none',
    color: theme.palette.text.secondary,
    fontWeight: 600,
    marginBottom: 16,
    '&:hover': { color: theme.palette.primary.main },
  },
  card: {
    display: 'flex',
    width: '100%',
    gap: 40,
    alignItems: 'flex-start',
    [theme.breakpoints.down('sm')]: { flexWrap: 'wrap', flexDirection: 'column', gap: 24 },
  },
  section: { flex: 1, minWidth: 0 },
  title: { fontSize: 'clamp(2rem, 4vw, 3rem)', lineHeight: 1.08, marginBottom: 14 },
  tagRow: { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 20 },
  tag: {
    fontWeight: 600,
    background: 'rgba(91,63,168,0.10)',
    color: theme.palette.primary.dark,
    '&:hover': { background: 'rgba(91,63,168,0.18)' },
  },
  message: { fontSize: '1.08rem', lineHeight: 1.7, color: theme.palette.text.primary, marginBottom: 26 },
  metaRow: { display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap', marginBottom: 8 },
  avatar: { backgroundColor: theme.palette.primary.main, color: '#fff', fontWeight: 700, width: 44, height: 44 },
  metaName: { fontWeight: 700 },
  metaNameLink: { color: theme.palette.primary.main, textDecoration: 'none' },
  metaDate: { color: theme.palette.text.secondary, fontSize: 14 },
  likeChip: { fontWeight: 600, color: theme.palette.secondary.dark, background: 'rgba(255,107,107,0.12)' },
  imageSection: {
    flex: '0 0 44%',
    position: 'sticky',
    top: 24,
    alignSelf: 'flex-start',
    [theme.breakpoints.down('sm')]: { flex: '1 1 auto', position: 'static', marginTop: 16 },
  },
  media: {
    borderRadius: '18px',
    objectFit: 'cover',
    width: '100%',
    maxHeight: '520px',
    boxShadow: '0 18px 50px rgba(31,27,46,0.16)',
  },
  commentsBlock: { marginTop: 8 },
  commentsHeading: { marginBottom: 16, fontWeight: 700 },

  // ── Comment list ──
  commentsList: {
    maxHeight: 380,
    overflowY: 'auto',
    marginBottom: 20,
    paddingRight: 4,
    '&::-webkit-scrollbar': { width: 4 },
    '&::-webkit-scrollbar-track': { background: 'transparent' },
    '&::-webkit-scrollbar-thumb': { background: 'rgba(91,63,168,0.25)', borderRadius: 4 },
  },
  commentItem: {
    display: 'flex',
    gap: 12,
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  commentAvatar: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    background: theme.palette.primary.main,
    color: '#fff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: 14,
    flexShrink: 0,
    textTransform: 'uppercase',
  },
  commentBody: {
    background: 'rgba(31,27,46,0.04)',
    borderRadius: '4px 14px 14px 14px',
    padding: '10px 14px',
    flex: 1,
  },
  commentAuthor: {
    fontWeight: 700,
    color: theme.palette.primary.dark,
    fontSize: '0.82rem',
    marginBottom: 3,
  },
  commentText: {
    color: theme.palette.text.primary,
    lineHeight: 1.6,
  },
  emptyComments: {
    color: theme.palette.text.secondary,
    fontStyle: 'italic',
    padding: '12px 0',
  },

  // ── Write a comment ──
  writeComment: {
    display: 'flex',
    gap: 12,
    alignItems: 'flex-start',
    paddingTop: 16,
    borderTop: '1px solid rgba(31,27,46,0.07)',
  },
  recommended: { marginTop: 40, paddingTop: 8 },
  recommendedHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  recommendedTitle: { fontWeight: 700, fontSize: '1.1rem' },
  seeAllLink: {
    color: theme.palette.primary.main,
    textDecoration: 'none',
    fontWeight: 600,
    fontSize: '0.85rem',
    '&:hover': { textDecoration: 'underline' },
  },
  recommendedPosts: {
    display: 'flex',
    gap: 16,
    overflowX: 'auto',
    paddingBottom: 8,
    '&::-webkit-scrollbar': { height: 5 },
    '&::-webkit-scrollbar-track': { background: 'transparent' },
    '&::-webkit-scrollbar-thumb': { background: 'rgba(91,63,168,0.22)', borderRadius: 4 },
  },
  recCard: {
    cursor: 'pointer',
    minWidth: 200,
    maxWidth: 220,
    flexShrink: 0,
    borderRadius: 14,
    overflow: 'hidden',
    boxShadow: '0 4px 18px rgba(31,27,46,0.10)',
    background: theme.palette.background.paper,
    border: '1px solid rgba(31,27,46,0.07)',
    transition: 'transform 0.18s ease, box-shadow 0.18s ease',
    '&:hover': {
      transform: 'translateY(-5px)',
      boxShadow: '0 10px 28px rgba(31,27,46,0.18)',
    },
  },
  recImg: { width: '100%', height: 136, objectFit: 'cover', display: 'block' },
  recContent: { padding: '10px 12px 14px' },
  recTitle: {
    fontWeight: 700,
    lineHeight: 1.35,
    marginBottom: 4,
    fontSize: '0.88rem',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  loadingPaper: {
    display: 'flex', justifyContent: 'center', alignItems: 'center',
    padding: '20px', borderRadius: '18px', height: '39vh',
  },
}));
